"""
Pydantic schemas for Reflection-related models.
"""
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, Literal


class ReflectionInputResponse(BaseModel):
    """Response model for reflection inputs."""
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "reflectionInputs": [
                    "How did your habit feel today?",
                    "What obstacles did you encounter?",
                    "What would make this habit easier?"
                ]
            }
        }
    )

    reflectionInputs: list[str] = Field(
        ..., description="List of reflection questions/inputs generated by LLM"
    )


# ----- Reflection flow items (Screen 1 & 2) -----


class InsightItem(BaseModel):
    """One insight card for the reflection flow (Screen 1)."""

    emoji: str = Field("💪", description="Emoji for the insight card")
    text: str = Field(..., description="Main insight text")
    highlight: Optional[str] = Field(
        None, description="Optional short highlight or takeaway"
    )


class ReflectionQuestions(BaseModel):
    """Two optional reflection questions for Screen 1."""

    question1: str = Field(
        ...,
        description="What helped you show up — even a little? (prompt for user)",
    )
    question2: str = Field(
        ...,
        description="On days it didn't happen, what made starting feel harder? (prompt)",
    )


class ExperimentSuggestion(BaseModel):
    """One experiment suggestion for Screen 2 (anchor, environment, or enjoyment)."""

    type: Literal["anchor", "environment", "enjoyment"] = Field(
        ..., description="Which habit lever this suggestion targets"
    )
    title: str = Field(..., description="Short title (e.g. Strengthen your anchor)")
    currentValue: str = Field(
        ..., description="Summary of user's current setup for this lever"
    )
    suggestedText: str = Field(
        ...,
        description="LLM-suggested 'Try this instead' text (one small experiment)",
    )
    why: str = Field(
        ...,
        description="One sentence explaining why this might help",
    )


class ReflectionItemsResponse(BaseModel):
    """Full reflection items generated from habit plan + streaks for the reflect screen."""

    insights: list[InsightItem] = Field(
        default_factory=list,
        description="0–2 insight cards based on streak/week patterns",
    )
    reflectionQuestions: ReflectionQuestions = Field(
        ...,
        description="Two reflection question prompts for Screen 1",
    )
    experimentSuggestions: list[ExperimentSuggestion] = Field(
        default_factory=list,
        description="Exactly 3 suggestions: anchor, environment, enjoyment",
    )


# ----- Save reflection answers -----


class ReflectionAnswerCreate(BaseModel):
    """Request model for saving reflection answers from the reflection flow."""

    habitId: str = Field(..., description="Habit ID")
    reflectionQ1: Optional[str] = Field(None, description="Answer to reflection question 1")
    reflectionQ2: Optional[str] = Field(None, description="Answer to reflection question 2")
    identityAlignmentValue: Optional[int] = Field(None, ge=0, le=100, description="Identity alignment slider value (0-100)")
    identityReflection: Optional[str] = Field(None, description="Free-text identity reflection")
    selectedExperiment: Optional[str] = Field(None, description="Selected experiment type (anchor/environment/enjoyment/maintain)")
    experimentText: Optional[str] = Field(None, description="User-edited experiment text for selected experiment (legacy)")
    experimentTexts: Optional[dict] = Field(None, description="All experiment texts keyed by type (anchor/environment/enjoyment)")
    weekRange: Optional[str] = Field(None, description="Week range string (e.g. 'Jan 27 – Feb 2')")


class ReflectionAnswerResponse(BaseModel):
    """Response model for saved reflection answers."""
    model_config = ConfigDict(
        populate_by_name=True,
        from_attributes=True,
    )

    id: str = Field(..., alias="_id")
    userId: str
    habitId: str
    reflectionQ1: Optional[str] = None
    reflectionQ2: Optional[str] = None
    identityAlignmentValue: Optional[int] = None
    identityReflection: Optional[str] = None
    selectedExperiment: Optional[str] = None
    experimentText: Optional[str] = None
    experimentTexts: Optional[dict] = None
    weekRange: Optional[str] = None
    createdAt: Optional[str] = None
