"""
Pydantic schemas for Reflection-related models.
"""
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional


class ReflectionInputResponse(BaseModel):
    """Response model for reflection inputs."""
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "reflectionInputs": [
                    "How did your habit feel today?",
                    "What obstacles did you encounter?",
                    "What would make this habit easier?"
                ]
            }
        }
    )
    
    reflectionInputs: list[str] = Field(..., description="List of reflection questions/inputs generated by LLM")
